name: Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/senergy-platform/mgw-module-validator:latest
            ghcr.io/senergy-platform/mgw-module-validator:${{ github.ref_name }}
  build-bin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Make Linux build dir
        run: mkdir -p linux_build/amd64 linux_build/arm64 linux_build/arm
      - name: Build Linux amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linux_build/amd64/mgw-module-validator -ldflags="-X 'main.version=${{ github.ref_name }}'" main.go
      - name: Build Linux arm
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o linux_build/arm/mgw-module-validator -ldflags="-X 'main.version=${{ github.ref_name }}'" main.go
      - name: Build Linux arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o linux_build/arm64/mgw-module-validator -ldflags="-X 'main.version=${{ github.ref_name }}'" main.go
      - name: Archive Linux
        run: tar -czvf mgw-module-validator-${{ github.ref_name }}-linux.tar.gz LICENSE README.md -C linux_build amd64 arm arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mgw-module-validator-${{ github.ref_name }}-linux.tar.gz